version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080' # Mapeia a porta 8080 do contêiner para a 8080 do host
    environment:
      - NODE_ENV=development
      - PORT=8080
      # Adicione outras variáveis de ambiente conforme necessário
    volumes:
      - .:/app # Mapeia o diretório atual do projeto para o diretório de trabalho no contêiner
      - /app/node_modules # Evita sobrescrever a pasta node_modules no contêiner
    command: yarn dev # Comando para iniciar a aplicação em modo de desenvolvimento